// Auto-generated by typescript_record_browser_flow from @playwright/mcp tool calls.
// Flow: home-page-load
// Dev server: http://localhost:5173
import { test, expect } from '@playwright/test';

test('home-page-load', async ({ page }) => {
  await page.goto('http://localhost:5173');
  await expect(page.getByText("Du kan allerede nu sikre dig en billet til Spis Grønt Dag #1").first()).toBeVisible();
});
